[configs]
domain = charlesgalea.com
email = mail@charlesgalea.com
your_name = Charles Galea
github = https://github.com/capgalea

; use this if you want comments on your blog posts, you will need to setup a new public report.
; using this tool = https://utteranc.es/
blog_comments = buildwithdan/my-blog-comments


; FOR CHAT BOT => you need to get the hubspot URL from here = https://www.hubspot.com/products/crm/live-chat?hubs_content=knowledge.hubspot.com%2Fchatflows%2Fcreate-a-bot&hubs_content-cta=create%2Fa%2Fchatflow%2Fwith%2Fa%2Fbot

hubspot = 

; your social links;
linkedin = https://www.linkedin.com/in/charles-galea-data-scientist/
; twitter = https://twitter.com/Dandeman891
 